// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.host.size.attributes.removed
// Description:Removing content attributes reverts to default size
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Removing content attributes reverts to default size");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  _assertSame(canvas.width, 120, "canvas.width", "120");
  canvas.removeAttribute('width');
  _assertSame(canvas.width, 300, "canvas.width", "300");
  t.done();
});
done();
